### PR TITLE
Ensure blog is installed before creating tables.

### LINKED ISSUE #73: Possible error during installation
When attempting to install WP on my wp-local-docker environment, I get the following error:

```
WordPress database error Table 'wordpress.wp_options' doesn't exist for query INSERT INTO `wp_options` (`option_name`, `option_value`, `autoload`) VALUES ('cavalcade_db_version', '2', 'no') ON DUPLICATE KEY UPDATE `option_name` = VALUES(`option_name`), `option_value` = VALUES(`option_value`), `autoload` = VALUES(`autoload`) made by include('phar:///usr/local/bin/wp/php/boot-phar.php'), include('phar:///usr/local/bin/wp/php/wp-cli.php'), WP_CLI\bootstrap, WP_CLI\Bootstrap\LaunchRunner->process, WP_CLI\Runner->start, WP_CLI\Runner->load_wordpress, require('wp-settings.php'), do_action('plugins_loaded'), WP_Hook->do_action, WP_Hook->apply_filters, HM\Cavalcade\Plugin\bootstrap, HM\Cavalcade\Plugin\create_tables, update_site_option, update_network_option, add_network_option, add_option
```

The problem appears to be line 98 in `inc/bootstrap.php`, within the `create_tables` function:
`	update_site_option( 'cavalcade_db_version', DATABASE_VERSION );`

The error is being caused by exactly what it says on the tin -- the `wp_options` table is not in existence at the time that this function call is made. It's possible that this is something wrong with my docker environment, but I note that no other plugins cause issues.

System details:
- Docker (Debian/Ubuntu)
- PHP 7.1
- WP 4.9.7, multisite

### LINKED ISSUE #79: Ensure WP Options table exists before boostrapping/creating tables.
The Cavalcade tables can be created prior to WP Core tables.

A couple of times I have seen the Cavalcade tables created in the database before the options table exists. Since Cavalcade started storing it's own DB version in the options table, this can now cause problems.

Prior to bootstrapping, a check to ensure the options table is created and populated will prevent this. For example:

```php
if ( ! get_option( 'db_version' ) ) {
  return;
}
```

### PR DESCRIPTION
**Pull request by peterwilsoncc**
WP fires the `plugins_loaded` hook during the install process, causing the Cavalcade tables to be created before the options table exists.

Without an options table, Cavalcade is unable to store the version of the database it is using it ends up considering all sites to be using version 1 of the database schema.

This adds a check to ensure `is_blog_installed() == true` before adding the Cavalcade database tables. I'm not sure how this affects multisite so would value any feedback.

Fixes #73

### CODE REVIEW

File: inc/namespace.php [hunk 1]
```diff
@@ -10,9 +10,12 @@
 function bootstrap() {
 	register_cache_groups();
 
-	if ( ! is_installed() ) {
-		create_tables();
+	if ( ! is_installed() && ! create_tables() ) {
+		return;
```
Comment (peterwilsoncc) [inline inc/namespace.php]: maybe run bootstrap `wp_install` action.

Comment (peterwilsoncc) [reply inc/namespace.php]: Tried this but `wp_install` fires before network install is complete so the option would end up in the `wp_options` table rather than the `wp_sitemeta` table where it belongs.

After a quick search I couldn't find an appropriate hook to use as an alternative so left it.

However, I did end up with a jobs table that looked like this after install which is not ideal.

_MySQL_5_7_25-0ubuntu0_16_04_2__Chassis_wordpress_wp_cavalcade_jobs

**Comment by joehoyle** [comment]
Hmm @roborourke @rmccue did we just fix something similar to this? Seem to remember needing to patch cavalcade when WP_INSTALLING was set... something along those lines?

**Comment by roborourke** [comment]
The issue is more to do with the runner, it doesn’t really handle a pre installation state and generates errors or quits the service entirely

**Comment by joehoyle** [comment]
Ok thanks @roborourke, @rmccue can you review and merge accordingly?

File: inc/namespace.php [hunk 2]
```diff
@@ -95,7 +105,42 @@ function create_tables() {
...
+	wp_cache_set( 'installed', true, 'cavalcade' );
 	update_site_option( 'cavalcade_db_version', DATABASE_VERSION );
+	/*
+	 * Ensure site meta is populated when running the WP CLI script to
+	 * install a network. Using the CLI, WP installs a single site with
+	 * wp_install() and then upgrades it to a multiste install immediately.
+	 *
+	 * Note: This does not work for multisite manual installs.
+	 */
+	add_filter( 'populate_network_meta', function( $site_meta ) {
```
Comment (rmccue) [inline inc/namespace.php]:
```suggestion
	add_filter( 'populate_network_meta', function ( $site_meta ) {
```

File: inc/namespace.php [hunk 3]
```diff
@@ -95,7 +105,42 @@ function create_tables() {
 
 	$wpdb->query( $query );
 
+	wp_cache_set( 'installed', true, 'cavalcade' );
 	update_site_option( 'cavalcade_db_version', DATABASE_VERSION );
+	/*
```
Comment (rmccue) [inline inc/namespace.php]:
```suggestion

	/**
```

File: inc/namespace.php [hunk 4]
```diff
@@ -95,7 +105,42 @@ function create_tables() {
...
+ * a single site install to a multisite install.
+ */
+function maybe_populate_site_option() {
+	if ( is_multisite() ) {
+		return;
+	}
+
+	$cavalcade_db_version = get_option( 'cavalcade_db_version' );
+
+	$set_site_meta = function( $site_meta ) use ( $cavalcade_db_version ) {
```
Comment (rmccue) [inline inc/namespace.php]:
```suggestion
	$set_site_meta = function ( $site_meta ) use ( $cavalcade_db_version ) {
```

**Comment by rmccue** [comment]
@peterwilsoncc can you update per above? (I can't commit to your fork :) )

**Comment by peterwilsoncc** [comment]
Requested changes committed along with updates from `master`.

**Comment by peterwilsoncc** [comment]
@roborourke @rmccue Bumped with master again to include the CI fix. Tests are now passing. 

It'll need some confirmation that the changes to plugin.php and namespace.php don't screw anything but testing locally it looks good to me.

**Comment by stuartshields** [comment]
@roborourke Can you approve and merge this PR in for @peterwilsoncc

**Comment by roborourke** [comment]
@stuartshields yeah, been meaning to test it locally. I was hoping to get #91 in first because the bulk of the tests are actually skipped right now

File: inc/namespace.php [hunk 5]
```diff
@@ -64,6 +69,11 @@ function is_installed() {
 }
 
 function create_tables() {
+	if ( ! is_blog_installed() ) {
+		// Do not create tables before blog is is installed.
```
Comment (roborourke) [inline inc/namespace.php]:
```suggestion
		// Do not create tables before blog is installed.
```
